spring:
  application:
    name: training-report-service
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "DIJMbOKj0rpWVC3GiK6dP+dCVaF0zaGHJH+Qq/ji9SI="

security:
  cors:
    allowed-origin: http://localhost:8081
    methods: "*"
    headers: "*"
    credentials: true