spring:
  application:
    name: training-report-service
  activemq:
    broker-url: failover:(tcp://localhost:61616)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/reportdb?authSource=admin
      auto-index-creation: true


logging:
  pattern:
    level: "%5p [${spring.application.name}] [correlationId=%X{correlationId}]"


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  messaging:
    workload-queue: trainer.workload.queue