spring:
  application:
    name: gym-crm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          my-client:
            client-id: gym-crm
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          my-client:
            token-uri: http://localhost:9000/oauth2/token


  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
  pattern:
    level: "%5p [${spring.application.name}] [correlationId=%X{correlationId}]"

jwt:
  secret: "1OLC84w+VsjVtqCuYOPgnQ9UOXy5aAFQP5BLgoeBEf0="

security:
  cors:
    allowed-origin: http://localhost:8080
    methods: "*"
    headers: "*"
    credentials: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

auth:
  client:
    id: "gym-crm"
    secret: "secret"

resilience4j:
  circuitbreaker:
    instances:
      training-report-service:
        failure-rate-threshold: 50
        sliding-window-size: 10