spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

jwt:
  secret: "1OLC84w+VsjVtqCuYOPgnQ9UOXy5aAFQP5BLgoeBEf0="

security:
  cors:
    allowed-origin: http://localhost:8080
    methods: "*"
    headers: "*"
    credentials: true
