storage.initialization.file.path=initial-data.json
config.database.datasource.url=jdbc:mysql://localhost:3306/gym?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
config.database.datasource.name=com.mysql.cj.jdbc.Driver
config.database.datasource.username=root
config.database.datasource.password=root
config.database.session.entities=com.epam.gymcrm.domain

#set true if you trainingType table is empty
config.datasource.initialize=true