storage.initialization.file.path=classpath:initial-data.json
config.database.datasource.url=jdbc:mysql://crm-mysql:3306/gym?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
config.database.datasource.name=com.mysql.cj.jdbc.Driver
config.database.datasource.username=root
config.database.datasource.password=root
config.database.session.entities=com.epam.gymcrm.domain

#set true if you TrainingType table is empty
config.datasource.initialize=false